services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=KinalSportsIN6BM
    ports:
      - "5436:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    command: node index.js
    ports:
      - "3129:3005"
    environment:
      - NODE_ENV=development
      - PORT=3005
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=KinalSportsIN6BM
      - DB_USERNAME=root
      - DB_PASSWORD=admin
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

volumes:
  db_data:
